### ISSUE TITLE
What are services.dll and services2.dll ?

### ISSUE THREAD

**Issue by darkurse** [tomap/nsis-extension#1]
Hi,

there are no links, credits regarding the plugins you've included in the package. So I don't know what API exactly you are using. In particular for services.dll and services2.dll ?

Can I actually add one myself ?
 => http://nsis.sourceforge.net/NSIS_Simple_Service_Plugin 

Would you mind publishing the url of the documentations for each of the plugins you are using ( En particulier services*.dll ? )

Thanks

**Comment by tomap** [comment]
Hi,
To be honest, I could not find where they come from. I suppose from NSIS site
for service2, here is the API:
```
services2::IsServiceRunning "w3svc"
Pop $0
  ${If} $0 == "Yes"
...

  ${Else}
...
  ${EndIf}
```
``services2::IsServiceInstalled "w3wp"`` work the same
Also:

```
services2::SendServiceCommandWait "start" "w3wp" "120"
  Pop $0
  ${If} $0 == "Ok"
...
  ${Else}
  ...
  ${Endif}
```
I'll also add this example in the readme + mention to the plugins

For Services.dll, I don't use it, so I don't know the API

As for SimpleSC, no problem, I can, unless you are good with Services2 ?

**Comment by darkurse** [comment]
Thank you for your answer! 
I cannot see the documentation for services2. I can only see the one for services and simpleSC. Do you have a link ?

I don’t need simpleSC as long as I can register and delete a service with services2

**Comment by darkurse** [comment]
@tomap , would you mind adding SimpleSC.dll as a plugin to this package please ?

Many thanks

**Comment by tomap** [comment]
No problem, I'll do that later this week.

**Comment by tomap** [comment]
Fixed in last build :)
