### ISSUE TITLE
Please add nsProcess support

### ISSUE THREAD

**Issue by yunfandev** [tomap/nsis-extension#3]
Please add support for nsProcess. 
It couldn't be better if you may add x86-unicode support

**Comment by tomap** [comment]
Just to be sure, are you talking about http://nsis.sourceforge.net/NsProcess_plugin ? (v1.6 ?)

There are already FindProcDll ( http://nsis.sourceforge.net/FindProcDLL_plug-in ) & KillProc ( http://nsis.sourceforge.net/KillProcDLL_plug-in ) 

Do you want me to add NsProcess ?

**Comment by tomap** [comment]
@MengYunfan Do you still need that? you did not answer my questions?

**Comment by Bhalddin** [comment]
@darkurse, I did a check and your first commit to your repo was in jun 17, while this repo is older than this. so obviously we can understand the direction and who should do the acknowledgement.
Have a nice day!

**Comment by yunfandev** [comment]
@tomap I don't need that any more. 😂😂😂
