### ISSUE TITLE
Add plugin InstallOptions.dll

### ISSUE THREAD

**Issue by darkurse** [tomap/nsis-extension#4]
Salut Thomas,

Would that be possible to add another plugin to your package ?
=> InstallOptions.dll

So that we can get a way to configure custom options.

Many thanks

**Comment by tomap** [comment]
Hi,

Are you talking about http://nsis.sourceforge.net/Docs/InstallOptions/Readme.html ?
This page seem to say that it's deprecated and does not provide a download link :(
Or another plugin?
Could you send a link to download and integrate that?

Thank you

**Comment by darkurse** [comment]
Oh ok. I can definitely convert my stuff to InstallOptions2. 

ps: I could be wrong but I got the InstallOptions plugin from the nsis installer I believe.

**Comment by tomap** [comment]
Indeed, it seems to be already part of the current installation zip:
https://github.com/tomap/nsis-extension/blob/master/nsis/nsis.zip
in the zip: nsis-3.03\Plugins\x86-ansi\InstallOptions.dll
Is it what you need?

**Comment by darkurse** [comment]
Damn. I totally forgot to get back to you on this !! Sorry about this.

Yes I would need that one but if you'd rather have InstallOptions2, let me know.

Thanks and sorry again about the delay.
