### ISSUE TITLE
How to add all files in the artefacts dir to the installer?

### ISSUE THREAD

**Issue by Crewman123** [tomap/nsis-extension#5]
Hi,
I am fairly new to nsis and vsts.

Is there a way I can use BUILD_ARTIFACTSTAGINGDIRECTORY variable to include all files of the artifacts dir?

Like:
File /r "BUILD_ARTIFACTSTAGINGDIRECTORY/*"

How do you guys do this?

**Comment by tomap** [comment]
Please use this forked repo: https://github.com/dev-maxima/nsis-extension This repo is no longer active

The new version is here: https://marketplace.visualstudio.com/items?itemName=bizeta.nsis-task

Please post your issues there
