### ISSUE TITLE
can you help me set up the CI for this Repo.

### ISSUE THREAD

**Issue by Bhalddin** [tomap/nsis-extension#6]
Hello Thomas,
During the last two days I tried to teach myself about VSTS Extensions and also about this wonderful project (nsis-extension). I tried to create a development environment to test your codes, So I installed Visual studio Code and  powershell plugin for it. I tried to figure out how to run it and I installed Microsoft/vsts-task-lib.  and I believe -if i'm not mistaken- you used this library in the nsis.ps1 file before vsts-task-lib change its functions (e.g. renaming invoke-tool to invoke-vststool for example).

I would like to know how to set up the CI for this Repo if I want to help you maintaining it. Also, what about the changes I mad to the nsis.p1 will it work?
Thanks.

**Comment by tomap** [comment]
Please use this forked repo: https://github.com/dev-maxima/nsis-extension This repo is no longer active

The new version is here: https://marketplace.visualstudio.com/items?itemName=bizeta.nsis-task


Please post your issue there
