### ISSUE TITLE
Add more plugins

### ISSUE THREAD

**Issue by darkurse** [tomap/nsis-extension#9]
Hello Toma,

would it be possible to add other dll on your vsts plugin ?

- https://nsis.sourceforge.io/Stack_plug-in
- https://nsis.sourceforge.io/ExecCmd_plug-in
- https://nsis.sourceforge.io/UserMgr_plug-in

Alternatively, could you expose a configurable field to set a custom path where all the dependencies we might need can be loaded from ?

What do you think ?

**Comment by tomap** [comment]
https://github.com/tomap/nsis-extension#looking-for-someone-to-maintain-this-project :(

**Comment by dev-maxima** [comment]
Hi Tomap ( @darkurse here ),

I have just forked your project at https://github.com/dev-maxima/nsis-extension

Could you please indicate how I can do CI and keep publishing your plugin on the devops marketplace ?

Thank you

**Comment by dev-maxima** [comment]
Salut @tomap , some news for me ?

**Comment by dev-maxima** [comment]
FYI, it's all done and available at 
https://marketplace.visualstudio.com/items?itemName=bizeta.nsis-task

**Comment by tomap** [comment]
Super, bravo. will update the readme to tell everyone
